---
metadata:
  version: "0.1.0-SNAPSHOT"
  description: "Mifos Standard Gradle Project"
  author: "Aleksandar Vidakovic <aleks@mifos.org>"
  dependency: "org.mifos.conventions.templates:mifos-conventions-templates-project:tgz:tpl:0.1.0-SNAPSHOT"
  instructions: |-
    Please initialize Git before you start building the project.
    Hit key 'F12' after you've generated the base project.
groups:
- name: "standard"
  description: "Standard Project Template"
  parameterGroups: []
  parameters:
  - name: "projectLicense"
    type: "SELECT_SINGLE"
    required: true
    description: "projectLicense"
    options:
    - "MPL-2.0"
    - "Apache-2.0"
    - "MIT"
    message: "License:"
    ignore: false
    default: "MPL-2.0"
  - name: "projectVendor"
    type: "STRING"
    required: true
    description: ""
    message: "Vendor:"
    ignore: false
    default: "Mifos Initiative"
  - name: "projectType"
    type: "SELECT_SINGLE"
    required: true
    description: "projectType"
    options:
    - "boot-imperative"
    - "boot-reactive"
    message: "Project Type:"
    ignore: false
    default: "boot-imperative"
  - name: "projectName"
    type: "STRING"
    required: true
    description: "projectName"
    message: "Project Name:"
    ignore: false
    default: "mifos-"
  - name: "projectGroupId"
    type: "STRING"
    required: true
    description: "projectGroupId"
    message: "Project Group ID:"
    ignore: false
    default: "org.mifos"
  - name: "projectDescription"
    type: "STRING"
    required: true
    description: "projectDescription"
    message: "Project Description:"
    ignore: false
    default: "Mifos [YOUR NAME HERE]"
  - name: "projectBasePackage"
    type: "STRING"
    required: true
    description: "projectBasePackage"
    message: "Project Base Package:"
    ignore: false
    default: "org.mifos"
  - name: "projectInceptionYear"
    type: "STRING"
    required: true
    description: "projectInceptionYear"
    message: "Project Inception Year:"
    ignore: false
    default: 2026
  - name: "developerUsername"
    type: "STRING"
    required: true
    description: "developerUsername"
    message: "Developer Username:"
    ignore: false
  - name: "developerFirstname"
    type: "STRING"
    required: true
    description: "developerFirstname"
    message: "Developer Firstname:"
    ignore: false
  - name: "developerLastname"
    type: "STRING"
    required: true
    description: "developerLastname"
    message: "Developer Lastname:"
    ignore: false
  - name: "developerEmail"
    type: "STRING"
    required: true
    description: "developerEmail"
    message: "Developer Email:"
    ignore: false
  - name: "developerTimezone"
    type: "SELECT_SINGLE"
    required: true
    description: "developerEmail"
    options:
    - "UTC-12"
    - "UTC-11"
    - "UTC-10"
    - "UTC-9"
    - "UTC-8"
    - "UTC-7"
    - "UTC-6"
    - "UTC-5"
    - "UTC-4"
    - "UTC-3"
    - "UTC-2"
    - "UTC-1"
    - "UTC"
    - "UTC+1"
    - "UTC+2"
    - "UTC+3"
    - "UTC+4"
    - "UTC+5"
    - "UTC+6"
    - "UTC+7"
    - "UTC+8"
    - "UTC+9"
    - "UTC+10"
    - "UTC+11"
    - "UTC+12"
    message: "Developer Timezone:"
    ignore: false
    default: "UTC"
  - name: "developerRoles"
    type: "SELECT_MULTI"
    required: false
    description: "developerRoles"
    options:
    - "developer"
    - "architect"
    - "owner"
    message: "Developer Roles:"
    ignore: false
  - name: "projectVersion"
    type: "STRING"
    required: false
    description: ""
    message: ""
    ignore: true
  - name: "role"
    type: "STRING"
    required: false
    description: ""
    message: ""
    ignore: true
  files:
  - path: "{{projectName}}/dco.txt"
    template: "__project_name__/dco.txt.peb"
    type: "PEBBLE"
  - path: "{{projectName}}/gradle/wrapper/gradle-wrapper.properties"
    template: "__project_name__/gradle/wrapper/gradle-wrapper.properties"
    type: "RAW"
  - path: "{{projectName}}/gradle/wrapper/gradle-wrapper.jar"
    template: "__project_name__/gradle/wrapper/gradle-wrapper.jar"
    type: "RAW"
  - path: "{{projectName}}/settings.gradle"
    template: "__project_name__/settings.gradle.peb"
    type: "PEBBLE"
  - path: "{{projectName}}/.gitattributes"
    template: "__project_name__/__gitattributes"
    type: "RAW"
  - path: "{{projectName}}/.gitignore"
    template: "__project_name__/__gitignore"
    type: "RAW"
  - path: "{{projectName}}/.github/copilot-ignore"
    template: "__project_name__/.github/copilot-ignore"
    type: "RAW"
  - path: "{{projectName}}/.github/dependabot.yml"
    template: "__project_name__/.github/dependabot.yml"
    type: "RAW"
  - path: "{{projectName}}/.github/CODEOWNERS"
    template: "__project_name__/.github/CODEOWNERS"
    type: "RAW"
  - path: "{{projectName}}/.github/PULL_REQUEST_TEMPLATE.md"
    template: "__project_name__/.github/PULL_REQUEST_TEMPLATE.md.peb"
    type: "PEBBLE"
  - path: "{{projectName}}/.github/workflows/release.yml"
    template: "__project_name__/.github/workflows/release.yml"
    type: "RAW"
  - path: "{{projectName}}/gradle.properties"
    template: "__project_name__/gradle.properties"
    type: "RAW"
  - path: "{{projectName}}/README.adoc"
    template: "__project_name__/README.adoc"
    type: "RAW"
  - path: "{{projectName}}/gradlew.bat"
    template: "__project_name__/gradlew.bat"
    type: "RAW"
  - path: "{{projectName}}/gradlew"
    template: "__project_name__/gradlew"
    type: "RAW"
  - path: "{{projectName}}/CLA.adoc"
    template: "__project_name__/CLA.adoc.peb"
    type: "PEBBLE"
  - path: "{{projectName}}/LICENSE"
    template: "__project_name__/LICENSE"
    type: "RAW"
  - path: "{{projectName}}/CODE_OF_CONDUCT.adoc"
    template: "__project_name__/CODE_OF_CONDUCT.adoc"
    type: "RAW"
  - path: "{{projectName}}/SECURITY.adoc"
    template: "__project_name__/SECURITY.adoc"
    type: "RAW"
  - path: "{{projectName}}/NOTICE"
    template: "__project_name__/NOTICE"
    type: "RAW"
  - path: "{{projectName}}/jreleaser.yml"
    template: "__project_name__/jreleaser.yml.peb"
    type: "PEBBLE"
  - path: "{{projectName}}/build.gradle"
    template: "__project_name__/build.gradle"
    type: "RAW"
