---
metadata:
  version: "0.1.0-SNAPSHOT"
  description: "Mifos Standard Gradle Project"
  author: "Aleksandar Vidakovic <aleks@mifos.org>"
groups:
- name: "standard"
  parameterGroups: []
  parameters:
  - name: "projectVendor"
    type: "STRING"
    required: true
    description: ""
    message: "Vendor:"
    default: "Mifos Initiative"
  - name: "projectType"
    type: "STRING"
    required: true
    description: "projectType"
    message: "Project Type:"
  - name: "projectName"
    type: "STRING"
    required: true
    description: "projectName"
    message: "Project Name:"
    default: "Mifos [YOUR NAME]"
  - name: "projectGroupId"
    type: "STRING"
    required: true
    description: "projectGroupId"
    message: "Project Group ID:"
    default: "org.mifos"
  - name: "projectDescription"
    type: "STRING"
    required: true
    description: "projectDescription"
    message: "Project Description:"
  - name: "projectBasePackage"
    type: "STRING"
    required: true
    description: "projectBasePackage"
    message: "Project Base Package:"
    default: "org.mifos"
  - name: "projectInceptionYear"
    type: "STRING"
    required: true
    description: "projectInceptionYear"
    message: "Project Inception Year:"
    default: "2026"
  - name: "developerUsername"
    type: "STRING"
    required: true
    description: "developerUsername"
    message: "Developer Username:"
  - name: "developerFirstname"
    type: "STRING"
    required: true
    description: "Developer Firstname:"
    message: "developerFirstname"
  - name: "developerLastname"
    type: "STRING"
    required: true
    description: "Developer Lastname:"
    message: "developerLastname"
  - name: "developerEmail"
    type: "STRING"
    required: true
    description: "Developer Email:"
    message: "developerEmail"
  - name: "developerTimezone"
    type: "STRING"
    required: true
    description: "Developer Timezone:"
    options:
    - "UTC-12"
    - "UTC-11"
    - "UTC-10"
    - "UTC-9"
    - "UTC-8"
    - "UTC-7"
    - "UTC-6"
    - "UTC-5"
    - "UTC-4"
    - "UTC-3"
    - "UTC-2"
    - "UTC-1"
    - "UTC"
    - "UTC+1"
    - "UTC+2"
    - "UTC+3"
    - "UTC+4"
    - "UTC+5"
    - "UTC+6"
    - "UTC+7"
    - "UTC+8"
    - "UTC+9"
    - "UTC+10"
    - "UTC+11"
    - "UTC+12"
    message: "developerTimezone"
    default: "UTC"
  - name: "developerRoles"
    type: "SELECT_MULTI"
    required: false
    description: "developerRoles "
    options:
    - "developer"
    - "architect"
    - "owner"
    message: "Developer Roles:"
  files:
  - path: "dco.txt.peb"
    template: "dco.txt.peb"
    type: "PEBBLE"
  - path: "gradle/wrapper/gradle-wrapper.properties"
    template: "gradle/wrapper/gradle-wrapper.properties"
    type: "RAW"
  - path: "gradle/wrapper/gradle-wrapper.jar"
    template: "gradle/wrapper/gradle-wrapper.jar"
    type: "RAW"
  - path: "settings.gradle.peb"
    template: "settings.gradle.peb"
    type: "PEBBLE"
  - path: ".github/copilot-ignore"
    template: ".github/copilot-ignore"
    type: "RAW"
  - path: ".github/dependabot.yml"
    template: ".github/dependabot.yml"
    type: "RAW"
  - path: ".github/CODEOWNERS"
    template: ".github/CODEOWNERS"
    type: "RAW"
  - path: ".github/PULL_REQUEST_TEMPLATE.md"
    template: ".github/PULL_REQUEST_TEMPLATE.md"
    type: "RAW"
  - path: ".github/workflows/release.yml"
    template: ".github/workflows/release.yml"
    type: "RAW"
  - path: "gradle.properties"
    template: "gradle.properties"
    type: "RAW"
  - path: "README.adoc"
    template: "README.adoc"
    type: "RAW"
  - path: "gradlew.bat"
    template: "gradlew.bat"
    type: "RAW"
  - path: "gradlew"
    template: "gradlew"
    type: "RAW"
  - path: "CLA.adoc"
    template: "CLA.adoc"
    type: "RAW"
  - path: "LICENSE"
    template: "LICENSE"
    type: "RAW"
  - path: "CODE_OF_CONDUCT.adoc"
    template: "CODE_OF_CONDUCT.adoc"
    type: "RAW"
  - path: "SECURITY.adoc"
    template: "SECURITY.adoc"
    type: "RAW"
  - path: "NOTICE"
    template: "NOTICE"
    type: "RAW"
  - path: "jreleaser.yml"
    template: "jreleaser.yml"
    type: "RAW"
  - path: "build.gradle"
    template: "build.gradle"
    type: "RAW"
